---
- name: Unmount hdfs volume
  hosts: all
  remote_user: centos
  become: true
  become_method: sudo
  become_user: root

  # fs variables
  vars:
    directoryPath:    '/hadoop'

  tasks:
  - name: unmount directory /hadoop
    # This will also add to /etc/fstab
    mount:
      path: "{{ directoryPath }}"
      state: unmounted



