---
- name: create and mount filesystem
  hosts: all
  remote_user: centos
  become: true
  become_method: sudo
  become_user: root

  # fs variables
  vars:
    device: '/dev/vdb'
    fstype: 'ext4'
    directoryPath:    '/hdfs'
    directoryOwner: 'centos'
    directoryGroup: 'centos'
    directoryMode: '0755'
    mountOptions: 'defaults'

  tasks:
  - name: Create a ext4 filesystem on /dev/vdb1 and check disk blocks
    filesystem:
      fstype: "{{ fstype }}"
      dev: "{{ device }}"

  - name: create directory if they don't exist
    file:
      path: "{{ directoryPath }}"
      state: directory

  - name: mount directory /hdfs
    # This will also add to /etc/fstab
    mount:
      path: "{{ directoryPath }}"
      src: "{{ device }}"
      fstype: "{{ fstype }}"
      opts: "{{ mountOptions }}"
      state: mounted

  - name:  Change permission on newly created directory and mounted fs
    file:
      owner: "{{ directoryOwner }}"
      group: "{{ directoryGroup }}"
      mode: "{{ directoryMode }}"
      recurse: yes
      path: "{{ directoryPath }}"

  - name: "Install ntpd"
    action: yum name=ntp state=present
    notify: restart-ntpd

  handlers:

    - name: restart-ntpd
      service: name=ntpd state=restarted enable=yes


